name: Build & Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Build & Publish
        env:
          GH_TOKEN: ${{ github.token }}
        run: npx electron-builder --win --publish always
